### ISSUE TITLE
呃，Preview 是图片唉，不应该是声音么？

### ISSUE THREAD

**Issue by PM-Ops** [sahuang/priconne-rainbow-fart#1]

**Comment by sahuang** [comment]
你好,preview目前设置的是在vscode打开的本地server中语音包预览, audio在Github README中不支持,所以似乎没法放声音.

不过之后我可能会在b站发个视频然后在readme link一下

**Comment by PM-Ops** [comment]
有视频就好，类似插件本体的demo就不错~

**Comment by sahuang** [comment]
已更新到README，B站demo视频：https://www.bilibili.com/video/BV1ez4y1Q7WW/
谢谢建议！
