### ISSUE TITLE
建议对音频文件剪裁

### ISSUE THREAD

**Issue by shitake2333** [sahuang/priconne-rainbow-fart#3]
使用pcr原版语音的一大问题是，大部分语音都对应很长一段角色台词。这使得经常关键词打完很久了还在一直播放。

如果这期间打了新的关键词会播放一半切过去播放新的，感觉十分的混乱。

建议对台词做一下剪裁，将一些打招呼和鼓励的语段单独剪出来，而将之后的长段语音删去。

**Comment by sahuang** [comment]
可以的 我下周会把每个角色较短的音频找出并做一个更新版的插件。

**Comment by sahuang** [comment]
Check [v0.3.0](https://github.com/sahuang/priconne-rainbow-fart/releases/tag/v0.3.0) for latest vocal pack with shorter vocals.
